### PR TITLE
146 csv download

### PR DESCRIPTION
**Pull request by allthesignals**
This PR adds a new download action for the report template. It also adds a Copy to Clipboard button, which should be reviewed for design input from @andycochran.

### CODE REVIEW

**Comment by andycochran** [comment]
Can the button exist outside (below?) the table? Would that take care of "Copy to Clipboard" being copied? And if we put each section of the table into its own table, will this still work with multiple tables? We'd probably want each table to have its own copy button.

**Comment by andycochran** [comment]
Maybe this could use the `{{fa-icon "clipboard"}}` icon and have a confirmation notice with an animation (like the "saved" animation on ZoLa).

**Comment by allthesignals** [comment]
> "Copy to Clipboard" is included in the content copied to the clipboard
Not much we can do about that, other than move it outside the table as a fixed div.

> Can the button exist outside (below?) the table? Would that take care of "Copy to Clipboard" being copied? And if we put each section of the table into its own table, will this still work with multiple tables? We'd probably want each table to have its own copy button.
Yeah totally. Multiple tables? No, it will only work with one table. It can be setup to point to a specific table. I'd prefer it to not be buried at the bottom, but it's your call. 

Separately, note the download button if you get a sec - I've sorted the data so it's nicer in the output.

**Comment by andycochran** [comment]
Since we're gonna separate the table into multiple tables, and move the header rows out of the table into `<hX>` elements, I think the place for the copy button is in each corresponding table's header. And similarly, the Download button could go in the page header.

**Comment by allthesignals** [comment]
@andycochran I think I should wait for #164 before addressing fixes here.

**Pull request merged**
