### PR TITLE
Updated median hhinc and faminc input variables

### LINKED ISSUE #419: Percents and percent moes are not appearing for a few variables in the 'Income & Benefits' section

### PR DESCRIPTION
**Pull request by EricaMaurer**
Updated variable labels for mdhhinc and mdfaminc to avoid duplicates

This should close #419

### CODE REVIEW

**Comment by allthesignals** [comment]
@EricaMaurer it looks like those variable names (mdhhiu10, etc...) are not coming back from the database - is there a data update for this?

**Comment by EricaMaurer** [comment]
@allthesignals there was an update end of December to fix the duplicate label problem.. 
"went through and changed any other duplicate labels that appeared once I added the Es to the special variables.. in case they cause any other issues. Everything is unique now. I can change them in the code if you want, but all the ones that changes are in the "special variable" sections-- hhpop in social changed to hhpop1, added "md" in front of all of the bins for hh income and fam income in economic, changed oochu in housing special variables to occhu4 and occhu5"

Let me know if you need the updated files.

**Comment by EricaMaurer** [comment]
File is too large to add to the issue

**Comment by allthesignals** [comment]
Bad news - this needs to be merged into https://github.com/NYCPlanning/labs-factfinder-api rather than here.

**Pull request closed without merging**
